### ISSUE TITLE
Where is the right place to ask questions about how to use Dclare for MPS?

### ISSUE THREAD

**Issue by markusvoelter** [ModelingValueGroup/DclareForMPS_Examples#1]

**Comment by WimBast** [comment]
Hi Markus! Thanks for asking. You can ask any questions by creating an issue in ModelingValueGroup/DclareForMPS. In the future we will have other means, but this is fine for us now.

**Comment by markusvoelter** [comment]
Done :-) https://github.com/ModelingValueGroup/DclareForMPS/issues/1
